version: 2
jobs:
  check:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout


      - restore_cache:
          name: "Restore dependencies cache"
          keys:
          - dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - dependencies-

      - run:
          name: "Install dependencies"
          command: yarn install

      - save_cache:
          name: "Cache dependencies"
          paths:
            - node_modules
          key: dependencies-{{ checksum "yarn.lock" }}


      - restore_cache:
          name: "Restore members cache"
          keys:
          - members

      - run:
          name: "Run the check"
          command: |
            yarn compile
            yarn start

      - save_cache:
          name: "Cache members"
          paths:
            - members.json
          key: members
workflows:
  version: 2
  check:
    jobs:
      - check
    triggers:
      - schedule:
          cron: "0 * * * *"

